# Generated by Django 2.0.2 on 2018-03-16 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Songofword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times', models.IntegerField(default=0)),
                ('indexes', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=300)),
                ('author_name', models.CharField(max_length=300)),
                ('song_url', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Words',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('songs', models.ManyToManyField(through='song.Songofword', to='song.Songs')),
            ],
        ),
        migrations.AddField(
            model_name='songofword',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.Songs'),
        ),
        migrations.AddField(
            model_name='songofword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.Words'),
        ),
    ]
