# Generated by Django 2.0.2 on 2018-02-26 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words',
            old_name='word',
            new_name='words',
        ),
    ]
