# Generated by Django 2.0.2 on 2018-02-26 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20180226_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='words',
            old_name='words',
            new_name='word',
        ),
        migrations.AddField(
            model_name='song',
            name='song_words',
            field=models.CharField(default=0, max_length=10000),
            preserve_default=False,
        ),
    ]
