# Generated by Django 2.0.2 on 2018-03-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20180318_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='song_content',
            field=models.CharField(default=0, max_length=10000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='songs',
            name='song_url',
            field=models.CharField(max_length=1000),
        ),
    ]
