# Generated by Django 2.0.2 on 2018-02-27 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0003_auto_20180226_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='Songwords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_words', models.CharField(max_length=10000)),
            ],
        ),
        migrations.RenameModel(
            old_name='Words',
            new_name='Word',
        ),
        migrations.RemoveField(
            model_name='song',
            name='song_words',
        ),
        migrations.AddField(
            model_name='songwords',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.Song'),
        ),
    ]
