# Generated by Django 2.0.2 on 2018-02-27 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_auto_20180227_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='song.Songwords'),
        ),
    ]
