# Generated by Django 2.0.2 on 2018-02-28 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0006_auto_20180228_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordsofsongs',
            name='num_songs',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='words',
            name='num_docs',
            field=models.IntegerField(),
        ),
    ]
