# Generated by Django 2.0.2 on 2018-03-13 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0008_auto_20180313_1409'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='words',
            name='num_docs',
        ),
    ]
