# Generated by Django 2.0.2 on 2018-03-13 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0009_remove_words_num_docs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='songs',
            name='word',
        ),
        migrations.AddField(
            model_name='words',
            name='indexes',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='words',
            name='song',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='song.Songs'),
            preserve_default=False,
        ),
    ]
